### ISSUE TITLE
Tela de Perfil do Usuário e Configurações do App

### ISSUE THREAD

**Issue by cristianprochnow** [Higia-App/higia-web#14]
Essas duas configurações são mais leves, pois o layout não é muito complexo e ainda envolve pouca coisa. Então, ao componentizar corretamente a página, os arquivos de código tendem a ser curtos.

Sendo assim, dá até de pegar alguma referência das telas do projeto Mobile, que seguem a mesma lógica. No modelo mobile da responsividade, a tela vai ficar  muito parecida com a nativa mobile, inevitavelmente.

[Protótipo](https://www.figma.com/file/pa37YRxTBhzgeSWelJxjPT/Higia?type=design&node-id=28%3A172&mode=dev)

![image](https://github.com/Higia-App/higia-web/assets/48127848/c9c25b7b-b0f7-4aa1-af8c-45634cdbf729)
![image](https://github.com/Higia-App/higia-web/assets/48127848/3c41abf0-f9cb-4fc5-a150-b6476fb30b42)

**Comment by gustapine** [comment]
Tela e estilização criadas :heavy_check_mark:
